### ISSUE TITLE
image for Slack post

### ISSUE THREAD

**Issue by tischi** [tischi/i2k-2020-s3-zarr-workshop#20]
@joshmoore @will-moore
The organisers asked us to post something in the conference Slack to announce our workshop. I thought maybe something like below image could be cute. I'd be happy to see an iteration on this by one of your kids if you like (unfortunately I don't have kids so I had to paint it myself ;-)
![IMG_2269](https://user-images.githubusercontent.com/2157566/100526457-6bb2ce80-31c9-11eb-9634-1f414aa9790b.jpg)

**Comment by joshmoore** [comment]
My kids think you did just fine. Will?

**Comment by will-moore** [comment]
It looks great - My kids can't think how to improve it, so go for it, thanks.

 Will.
________________________________

**Comment by joshmoore** [comment]
sent to organizers.
